AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Create Resource
  - StepFunctions
  - EventBridge

Parameters:
  EnvironmentVariable:
    Description: 環境変数
    Type: String
    Default: dev
  VersionVariable:
    Description: バージョン番号
    Type: String
    Default: ver1
  StepFunctionsExecutionRole:
    Description: Step Functionsの実行ロール
    Type: String
    Default: arn:aws:iam::<AWSアカウントID>:role/StepFunctionsExecutionRole
  SageMakerProcessingImage:
    Description: SageMakerのProcessingJobを動かすImage
    Type: String
    Default: <AWSアカウントID>.dkr.ecr.ap-northeast-1.amazonaws.com/tst-teamaya-ecr:latest

Resources:
  # =======Step Functions for ProcessingJob======== #
  DevMLPipelinesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${EnvironmentVariable}-sample-ml-pipelines-${VersionVariable}
      DefinitionUri: ../../statemachine/sample-ml-pipelines-ver1.asl.json
      DefinitionSubstitutions:
        ProcessingJobRole: !Ref StepFunctionsExecutionRole
        ProcessingImage: !Ref SageMakerProcessingImage
        ProcessingEnvironment: !Ref EnvironmentVariable
      Role: !Ref StepFunctionsExecutionRole
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Description: パイプライン用のスケジューラー
            Enabled: False
            Name: !Sub ${EnvironmentVariable}-sample-ml-pipelines-${VersionVariable}
            Schedule: "cron(0 16 * * ? *)"
