version = 0.1
[default]
[default.deploy.parameters]
stack_name = "prod-sample-codepipeline"
s3_bucket = "aws-sam-cli-managed-samclisourcebucket-prod-sample-codepipeline"
s3_prefix = "prod-sample-codepipeline"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
